name: Auto Merge backend-dev & frontend-dev into dev

on:
  push:
    branches:
      - backend-dev
      - frontend-dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configurar usuário do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Buscar todas as alterações
        run: git fetch origin dev

      - name: Fazer merge na branch dev
        run: |
          git checkout dev
          git merge origin/backend-dev --no-ff -m "Merge automático de backend-dev"
          git merge origin/frontend-dev --no-ff -m "Merge automático de frontend-dev"
          git push origin dev
